### ISSUE TITLE
Request: Export

### ISSUE THREAD

**Issue by myrinx** [garethr/zapr#1]
Hey,

Awesome code!!! Just a small favor to ask to be added in :)

Can you please make an export function too? So that the summary or json can be written to a file location? Now i work through zapr > output.txt, but i rather would  like to see whats going on on the screen too :)

Thanks!!

**Comment by vpereira** [comment]
hey @wickett  I'm the author of   owasp-zap ruby api. I think its my fault, that the zap log is being sent to stdout. I pushed some code to fix it. Let me know if it works for you.
btw @garethr, awesome stuff! if you need more features implemented, just let me know ;)

**Comment by garethr** [comment]
Hi @myrinx. Your best bet to do that is to use `tee`, which is super useful and much more general purpose than adding something to zapr. http://en.wikipedia.org/wiki/Tee_(command). So

```
zapr | tee output.txt
```

That will record the results in output.txt AND print to stdout.

**Comment by myrinx** [comment]
works fine, thanks! Sorry for the late reply
